server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.40.129:1111   #配置Nacos地址   服务注册的地址  linux

management:
  endpoints:
    web:
      exposure:
        include: '*'     #监控  *为全部暴露
