server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Willi-Lau/springcloud-study-config.git #GitHub上面的git仓库名字 http  ssh报错
          ####搜索目录
          search-paths:
            - springcloud-study-config
          force-pull: true   #          账户密码
          username: 2284069530@qq.com
          password: WG12315qwert..
      ####读取分支
      label: main


#      测试输入   Postmen   http://127.0.0.1:3344/main/config-dev.yml   就可以读取到信息


#rabbitmq相关配置
#rabbitmq:
#  host: localhost
#  port: 5672
#  username: guest
#  password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

###rabbitmq相关配置,暴露bus刷新配置的端点
#management:
#  endpoints: #暴露bus刷新配置的端点
#    web:
#      exposure:
#        include: 'bus-refresh'


