server:
  port: 8001



spring:
  application:
    name: cloiu-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/fruit?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
    type-aliases-package: com.lwy.demo.entity
    mapper-locations: mapper/*.xml
